### PR TITLE
Include socket.io code as script

### PR DESCRIPTION
**Pull request by coderextreme**
I have tried to include Socket IO as a script.  I haven't used the PlayCanvas GUI yet.  I get an error that this.entity.script.SocketIO is undefined.  I think this is because it's not hooked up in the PlayCanvas GUI yet.

### CODE REVIEW

**Comment by coderextreme** [comment]
Just added MultiplayerServer.js code.  No longer really need to have app.js.  But do need to run MultiplayerServer.js on the server still, with node.js or io.js

**Comment by coderextreme** [comment]
Commented out socket code so we can load into PlayCanvas.

**Comment by coderextreme** [comment]
What I did was if io didn't exist, then don't fail.

**Comment by r2d2Proton** [comment]
I haven't modified the source since this mornings commit, and GitHub is complaining that it cannot be automatically merged. Do you know why this is?

**Comment by coderextreme** [comment]
Probably we both made changes to the same file.  Go ahead and reject the
pull request.  I can resubmit.

**Comment by coderextreme** [comment]
Sometimes you have to do the merge by hand.  Search for =======

**Comment by coderextreme** [comment]
Okay, this should be up to date with r2d2 now (whew)

**Comment by r2d2Proton** [comment]
Yes, I know. . .it took me a while just do perform the first merge, which in SVN terms would have been quite trivial.

**Pull request merged**
